tap "anomalyco/tap"
tap "tw93/tap"
tap "my-monkeys/tap"

# ──────────────────────────────────────────────
# Shared (all platforms)
# ──────────────────────────────────────────────
brew "atuin"
brew "fzf"
brew "gh"
brew "helix"
brew "jq"
brew "lsd"
brew "ruff"
brew "starship"
brew "uv"
brew "yazi"
brew "zoxide"
brew "herdr"


# ──────────────────────────────────────────────
# macOS only
# ──────────────────────────────────────────────
if OS.mac?
  brew "mole"
  brew "python@3.14"
  brew "pipx"
  cask "font-fira-mono-nerd-font"
  brew "anomalyco/tap/opencode"
  cask "iina"
  cask "maccy"
  cask "ghostty"
  cask "snipaste"
  cask "visual-studio-code"
  cask "tailscale-app"
  cask "opensuperwhisper"
  cask "vivaldi"
end

# ──────────────────────────────────────────────
# Linux only
# ──────────────────────────────────────────────
if OS.linux?
  brew "transmission-cli"
  brew "wtfutil"
end
