
[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true # Wraps at 80 chars by default   

[language.formatter]
command = "ruff"
args = ["format", "-"]

